<?php

/**
 * @file
 * Installation file for system_status.
 */

/**
 * Implements hook_install().
 *
 * Creates a unique set of tokens for this installation.
 */
function centralization_agent_install() {
  $encrypt = \Drupal::service('centralization_agent.encrypt');
  $config = \Drupal::configFactory()->getEditable('centralization_agent.settings');
  $config->set('centralization_agent_token', $encrypt::getToken());
  $config->set('centralization_agent_encrypt_token', $encrypt::getToken());
  $config->save();
}
