<?php

/**
 * @file
 * Installation file for system_status.
 */

/**
 * Implements hook_install().
 *
 * Creates a unique set of tokens for this installation.
 */
function centralization_agent_install() {
  $encrypt = \Drupal::service('centralization_agent.encrypt');
  $config = \Drupal::configFactory()->getEditable('centralization_agent.settings');
  if(empty($config->get('shared_token')) || empty($config->get('encrypt_key'))) {
    $config->set('shared_token', $encrypt::getToken());
    $config->set('encrypt_key', $encrypt::getEncryptKey());
    $config->save();
  }
}
