<?php

/**
 * @file
 * Installation file for system_status.
 */

/**
 * Implements hook_install().
 *
 * Creates a unique set of tokens for this installation.
 */
function centralization_agent_install() {
  $encrypt = \Drupal::service('centralization_agent.encrypt');
  $config = \Drupal::configFactory()->getEditable('centralization_agent.settings');
  if(empty($config->get('shared_token')) || empty($config->get('encrypt_key'))) {
    $config->set('shared_token', $encrypt::getToken());
    $config->set('encrypt_key', $encrypt::getEncryptKey());
    $config->save();
  }
}

/**
 * Génère les tokens shared_token et encrypt_key s'ils n'existent pas.
 */
function centralization_agent_update_10001() {
  $config = \Drupal::configFactory()->getEditable('centralization_agent.settings');

  if (empty($config->get('encrypt_key'))) {
    $config->set('shared_token', Crypt::randomBytesBase64(32));
    $config->set('encrypt_key', base64_encode(random_bytes(32)));
  }

  $config->save();

  return t('Les tokens shared_token et encrypt_key ont été générés.');
}
