centralization_agent.settings:
  type: config_object
  label: 'Centralization Agent settings'
  mapping:
    shared_token:
      type: string
    encrypt_key:
      type: string
    allowed_ips:
      type: sequence
      label: 'Allowed IPs'
      sequence:
        type: string
