centralization_agent.settings:
  type: config_object
  label: 'Centralization Agent settings'
  mapping:
    shared_token:
      type: string
    encrypt_key:
      type: string
    https_required:
      type: boolean
    show_debug_info:
      type: boolean
    allowed_ips:
      type: sequence
      label: 'Allowed IPs'
      sequence:
        type: string
    vscode_server_relative_path:
      type: string
